poller/urls.py
from django.contrib import admin
from django.urls import path, include

from polls import views

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.show, name='show' ),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice


def home(request):
    return render(request, 'base.html')

def index(request):
    question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'question_list': question_list}
    return render(request, 'polls/index.html', context)

def show(request, question_id):
    try:
        question_with_choices = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question doesnt exist")
    return render(request, 'polls/show.html', {'question_with_choices': question_with_choices})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        return render(request, 'polls/show.html', {
            'question_with_choices': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:show', args=(question.id,)))

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <title>Pollster {% block title %}{% endblock %}</title>
</head>

<body>
  {% include 'partials/_navbar.html' %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center">
        {% block content %}
        <p class="lead py-5">
          <a href="{% url 'polls:index' %}" class="btn btn-md btn-danger">Vote Now</a>
        </p>
        {% include 'partials/_voting.html' %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

polls/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-dark justify-content-center">
  <a href="{% url 'home' %}"><span class="navbar-brand m-auto h1">Poller.</span></a>
</nav>

polls/templates/partials/_voting.html
<div class="m-auto">
  <img
    src="https://npr.brightspotcdn.com/dims4/default/54149f0/2147483647/strip/true/crop/900x857+0+0/resize/880x838!/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Flegacy%2Fsites%2Fwemu%2Ffiles%2F202201%2F25229-7-voting-box-file.png"
    alt="" width="500px">
</div>

polls/templates/polls/index.html
{% extends 'base.html' %}
{% load humanize %}

{% load custom_filters %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h3>Avaiable <span class="text-warning">polls.</span></h3>
      <hr />
      {% for question in question_list %}
      <div class="card mb-3">
        <div class="card-body">

          {% if question.pub_date|timesince|naturaltime <= '2 weeks' %}
          <h5 class="card-title">{{ question.question_text }} </h5>
          <p class="text-danger">{{ question.pub_date|time_difference }} <span class="text-secondary">left to
              vote</span></p>
          {% else %}
          <p class="text-danger text-bold">Voting has been closed!</p>
          {% endif %}

          <a class="btn btn-sm btn-success {% if question.pub_date|timesince|naturaltime >= '2 weeks' %}disabled{% endif %}"
            href="{% url 'polls:show' question.id %}">Vote now</a>

        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/show.html
{% extends 'base.html' %}
{% block content %}

{% if error_message %}
<div class="alert alert-danger mt-2" role="alert">
  <strong>{{ error_message }}</strong>
</div>
{% endif %}

<div class="container mt-4">
  <h3>{{ question_with_choices.question_text }}</h3>
  <form action="{% url 'polls:vote' question_with_choices.id %}" method="post">
    {% csrf_token %}
    <div class="list-group mt-4">
      {% for choice in question_with_choices.choice_set.all %}
      <div class="list-group-item">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
          value="{{ choice.id }}" />
        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }} -
          {{choice.votes}}</label>
      </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary mt-4">Vote</button>
  </form>
</div>

{% endblock %}